on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install
        run: npm ci
      - name: checkout-published
        run: git worktree add -B gh-pages build origin/gh-pages
      - name: publish-changes
        run: |
          git add .
          git config --global user.name "Continuous Security Reports"
          git config --global user.email "continuous-security-reports@acode.ninja"
          git commit -m "Publishing changes"
          git push
        working-directory: build
